
services:
  hub:
    image: selenium/hub:4.20
    environment:
      - SE_GRID_MAX_SESSION=5
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  chrome:
    image: selenium/node-chrome:4.20
    shm_size: '2g'
    depends_on:
      hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.20
    shm_size: '2g'
    depends_on:
      hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  vendor-portal:
    image: aqadir9456/seleniium
    depends_on:
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - THREAD_COUNT=1
      - TEST_SUITE=Portal_Test.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output


  # flight-reservation:
  #   image: aqadir9456/seleniium
  #   depends_on:
  #     - chrome
  #   environment:
  #     - BROWSER=chrome
  #     - HUB_HOST=hub
  #     - THREAD_COUNT=1
  #     - TEST_SUITE=testng.xml
  #   volumes:
  #     - ./output/flight-reservation:/home/selenium-docker/test-output
